name: stack_overflow_lite
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^1.0.3
  flutter_mobx: ^1.1.0+2
  asuka: ^2.0.0
  mobx: ^1.2.1+1
  firebase_core: ^1.2.0
  flutter_modular: ^3.2.2+1
  firebase_auth: ^1.2.0
  dartz: ^0.10.0-nullsafety.2
  string_validator: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
